POST http://127.0.0.1:5000//api/registration/
Content-Type: application/json

{
  "username": "PirogovaDasha",
  "password": "?",
  "name": "Dasha",
  "surname": "Pirogova",
  "is_mdfive": "0"
}

###
